name: CI

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check pre
        run: |
          pwd
          ls -la
      - uses: actions/checkout@v1
      - name: Check post
        run: |
          pwd
          ls -la
      - name: Check folderA
        run: |
          pwd
          cd folderA
          cat fileA.txt
      - name: Check folderB
        run: |
          pwd 
          cd folderB
          cat fileB.txt



